"""empty message

Revision ID: 009bb77131e2
Revises: b4635d5f2b0b
Create Date: 2026-02-11 15:01:06.161119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '009bb77131e2'
down_revision = 'b4635d5f2b0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acessos',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('cartao_id', sa.String(length=40), nullable=False),
    sa.Column('tipo_acesso', sa.String(length=120), nullable=False),
    sa.Column('local', sa.String(length=120), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cartoes',
    sa.Column('dono_id', sa.Integer(), nullable=False),
    sa.Column('chave_cartao', sa.String(length=120), nullable=False),
    sa.Column('tem_acesso', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chave_cartao')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cartoes')
    op.drop_table('acessos')
    # ### end Alembic commands ###
