"""empty message

Revision ID: 1eff5fc91bde
Revises: 6feeb799a3d6
Create Date: 2025-11-26 15:38:20.957658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1eff5fc91bde'
down_revision = '6feeb799a3d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moderadores', schema=None) as batch_op:
        batch_op.alter_column('senha_hash',
                              existing_type=sa.VARCHAR(length=120),
                              type_=sa.String(length=512),
                              existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moderadores', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('moderadores_senha_hash_key'), [
                                          'senha_hash'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('senha_hash',
                              existing_type=sa.String(length=512),
                              type_=sa.VARCHAR(length=120),
                              existing_nullable=False)

    # ### end Alembic commands ###
