"""empty message

Revision ID: 62cb9dad5292
Revises: e4fd7c38da4b
Create Date: 2025-12-04 16:18:52.335267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62cb9dad5292'
down_revision = 'e4fd7c38da4b'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.create_unique_constraint("uq_clientes_email", ['email'])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
