"""empty message

Revision ID: 6feeb799a3d6
Revises: 5f1202da2b3a
Create Date: 2025-11-14 15:38:55.294556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6feeb799a3d6'
down_revision = '5f1202da2b3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acessos',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('cartao_id', sa.Integer(), nullable=False),
    sa.Column('tipo_acesso', sa.String(length=120), nullable=False),
    sa.Column('local', sa.String(length=120), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cartoes',
    sa.Column('dono_id', sa.Integer(), nullable=False),
    sa.Column('chave_cartao', sa.String(length=120), nullable=False),
    sa.Column('tem_acesso', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chave_cartao')
    )
    op.create_table('clientes',
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('documento', sa.String(length=120), nullable=False),
    sa.Column('tem_acesso', sa.Boolean(), nullable=False),
    sa.Column('tipo', sa.String(length=120), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('documento')
    )
    op.create_table('moderadores',
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('senha_hash', sa.String(length=120), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moderadores')
    op.drop_table('clientes')
    op.drop_table('cartoes')
    op.drop_table('acessos')
    # ### end Alembic commands ###
