"""empty message

Revision ID: d177e36a865a
Revises: 009bb77131e2
Create Date: 2026-02-11 15:03:25.200535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd177e36a865a'
down_revision = '009bb77131e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cartoes', schema=None) as batch_op:
        batch_op.alter_column('dono_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cartoes', schema=None) as batch_op:
        batch_op.alter_column('dono_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
