"""empty message

Revision ID: e4fd7c38da4b
Revises: 1eff5fc91bde
Create Date: 2025-11-26 16:49:14.499336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4fd7c38da4b'
down_revision = '1eff5fc91bde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moderadores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ativo', sa.Boolean(), server_default=sa.text('true'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moderadores', schema=None) as batch_op:
        batch_op.drop_column('ativo')

    # ### end Alembic commands ###
